pyproject.toml
src/amltk/scheduling/scheduler.py
tests/scheduling/test_scheduler.py

Allows a function to be run sometime later after a delay, within the scheduler. Can act as an alternative to using `timeout` in the `run()` but also allows for some more intricate logic if needed.
Really is just a wrapper around [`asyncio.call_later()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_later) but allow users to access it from a syncronous context.
```python
from amltk.scheduling import Scheduler
scheduler = Scheduler.with_processes(1)
def fn() -> int:
print("Ending now!")
scheduler.stop()
@scheduler.on_start
def schedule_fn() -> None:
scheduler.call_later(1, fn)  # Call this function 1 second later
scheduler.run(end_on_empty=False)
```
Tests still need to be fixed for mac/windows but they are unrelated to this.

feat(scheduler): method `call_later`

---

src/amltk/pipeline/node.py
tests/pipeline/test_request.py

Previously, the `case` statement was locally overriding the value `k` which caused param requests to be placed at the wrong key in the `node.config` when doing `configure(..., params={...})`
```python
for k, request in config.items():  # `k` defined here
match request:
case ParamRequest(key=k) if k in _params:  # Whoops
new_config[k] = _params[request.key]
```
This was fixed and added some tests for the main behaviours of `request()`
@LennartPurucker I'll wait this time ;)

fix(pipeline): `request()` correctly sets config key

---

docs/reference/scheduling/executors.md
src/amltk/scheduling/executors/dask_jobqueue.py
src/amltk/scheduling/scheduler.py

Previously, `dask-jobqueue` based executors would default to `adapt()`. However this would lead to some unpredicted behaviour where not enough jobs were spawned and seemed to under-utilize resources with very few jobs. We changed the default to `scale()` but leave the option to set `adaptive=`.
There was a slight bug which caused an endless loop which should be fixed now.

fix(dask-jobqueue): Prevent endless __enter__ cycle

---

examples/dask-jobqueue.py
examples/hpo.py

Just a brief example which basically just copies the [HPO example](https://automl.github.io/amltk/latest/examples/hpo/) but replaces `Scheduler.with_processes()` to use dask jobqueue.
---
Some brief testing confirms issue with scaling of BO optimizers. With 128 workers and 2 minutes available, SMAC reached just under 500 evaluations and went overtime drastically. With 32 workers, it reached ~900. From watching the logs flying by, it seems that most of the time was just spent waiting in the main process for SMAC as it gets crushed under the incoming information.
@LennartPurucker tagging you as it might interest you for the future to know how this is used for the ensembling
@mfeurer @KEggensperger We should think of a proper way to utilize this to compare the capabilities of Optimizers to …

doc(dask-jobqueu): Add an example for runnig with SLURM

---

tests/test_examples.py

The tests tried to run the dask-example and would just hang. This test is not meant to be run without a slurm cluster available. The fix is check example files have the `"doc-runnable"` flag (in the first 10 lines?) which is what the `docs/example_runner.py` does to check if it should run and render it.

ci: Only test `"doc-runnable"` examples

---

pyproject.toml

The original one was not recognized by PyPI and would prevent a build upload

fix(pyproject): Change to recognized classifier for PyPI

---

src/amltk/_doc.py
src/amltk/pipeline/components.py

Previously, the `doc_print` command would do nothing if the renderable was not a pipeline, corrected now

fix(_doc): Catch missing else statement

---

src/amltk/pipeline/components.py
tests/pipeline/test_configuring.py

Previously, when configuring, a `Choice` would propogate the config to
all child nodes. This was problematic when a `config_transform` of a
child expected something to be in the config. These contents were
usually not there as well...it was chosen.
See the test case `expected_b`, where previously `transform_a` would be called, even if `b` was chosen, causing an error to occur.

fix(pipeline): configure only operates on chosen choice

---

docs/reference/scheduling/queue_monitor.md
mkdocs.yml
pyproject.toml
src/amltk/scheduling/queue_monitor.py
tests/scheduling/test_monitor.py

Implement a `QueueMonitor` method to view the efficiency of your Scheduler setup.
Tests included. Output from `5` seconds with 8 workers and a simple `x + 1` task. Plot with `(50, "ms")` interval mean.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

feat(Scheduler): Monitor to view efficiency

---

src/amltk/data/dtype_reduction.py
tests/data/test_dtype_reduction.py

Fixes #134 
Extra check during `reduce_int_span` now calls out to pandas when dealing with a `Series`. Previously, the `np.result_type` would return a `np.dtype` which has no support for nullables, which are allowed by pandas, through something like `"Int64"`
https://pandas.pydata.org/docs/user_guide/integer_na.html
See tests
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

fix(data): `reduce_int_span` with nullable dtypes

---

docs/guides/scheduling.md
src/amltk/scheduling/events.py
src/amltk/scheduling/task.py

Fixes: #148 
The parameter `limit=` was a bit vague to what it implied. `max_calls=` is a little more clear
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

refactor(Scheduling): `limit` -> `max_calls`

---

src/amltk/optimization/history.py

The issue is that previously this would error by recursion, instead of explicitly saying what went wrong. This error would be avoided by someone using a type-checker. Since this should accomodate notebook users who do not have these features readily available, we explicitly raise an error.
tldr; `str` is iterable so it kept looping on itself
```python
from amltk.optimization import History
history = History()
history.add({"anything": 1})
```

fix(History): Explicitly check type in add()

---

docs/guides/scheduling.md
src/amltk/scheduling/scheduler.py
tests/scheduling/test_scheduler.py

This PR follows #213 conceptually, allowing users to `"raise"`, `"continue"` or `"end"` when a future was cancelled from the Scheduler.
The other major point is that the Literal argument `"ignore"` was renamed to `"continue"` to be more descriptive in terms of behaviour. The reason being is that `"ignore"` made it seem like the error would simply be ignored. This was not True as the `Scheduler` would still emit the exception, it was just continue after it.
Lastly, this PR does some cleanup to reduce the technical debt incurred by PR #213

feat(Scheduler): Respond to cancelled futures

---

tests/scheduling/plugins/test_call_limiter_plugin.py
tests/scheduling/plugins/test_comm_plugin.py
tests/scheduling/plugins/test_pynisher_plugin.py
tests/scheduling/plugins/test_threadpoolctl_plugin.py
tests/scheduling/test_scheduler.py
tests/store/test_bucket.py

Noticed that they weren't specified, but good to be explicit that they should be function scope

test: Update fixtures to be explicitly function scope

---

src/amltk/pipeline/__init__.py
src/amltk/pipeline/node.py
src/amltk/pipeline/ops.py
tests/pipeline/test_node.py
tests/pipeline/test_ops.py

This PR implements a way to quickly factorize a pipeline with choices into individual pipelines where those choices are instead fixed (see image below for example).
The default behavior is to assume we want to create a new child for every child in a `Choice` and that to create this new pipeline, we just mutate the node and set that as it's only child.
```python
if isinstance(node, Choice):
possible_choices = [node.mutate(nodes=(child,)) for child in node.children]
```
Edit:
By default this applies at all depths of the tree but you can also provide a `min_depth=` and `max_depth=` by which to regulate where splitting should occur. If you want to factor at a particular node you know in advance, please use `factor_by=` as a predicate as stated below. If you really need some more control, the …

feat(Pipeline): `factorize()` a pipeline into its possibilities

---

src/amltk/scheduling/plugins/pynisher.py
tests/scheduling/plugins/test_pynisher_plugin.py

If a task which was used for a `Trial`, such as those when optimizing trials from an Optimizer, exceeded it's constraints, it would previously just be a generic `Task` exception which would have to be handled with `@task.on_exception`. However it's often the case that we would rather get back a `Trial.fail()` through `@task.on_result` such that we can handle it in a uniform manner with other trials that failed. This also caused issues with the scheduler error handling mechanism for which #213 was introduced.
The new default behaviour of the `PynisherPlugin` is to auto-detect if a `Task` contains a `Trial`. If so and the `Task` exceeded one of it's constraints, it would simply return `task.fail()` with the relevant pynisher exception filled in. This behavior can be disabled with …

feat(Pynisher): Detect tasks with `Trial` to report `FAIL`

---

src/amltk/optimization/optimizer.py
src/amltk/optimization/optimizers/neps.py
src/amltk/optimization/optimizers/optuna.py
src/amltk/optimization/optimizers/smac.py
tests/optimizers/test_optimizers.py

This PR extends the `.ask()` of Optimizers to include an integer `ask(n: int | None = None)` where the default behaviour is to get a single configuration, while giving an `n` returns an iterator of configurations.
By default, optimizers which work in a sequential manner can simply call to them selves in a repeated fashion:
```python
if n is not None:
return (self.ask(n=None) for _ range(n))
```
This PR is more aimed at supporting optimizers which support batched `ask`s. This can provide both theoretical improvements but also more optimized improvements. For example, if there is an evolutionary algorithm, computing `n` children can be faster than computing `1` child `n` times.
TODO:
* Currently every optimizer implemented just defaults to the sequential ask mechanism provided in the …

feat(Optimizer): Allow for batch ask requests

---

src/amltk/_richutil/__init__.py
src/amltk/_richutil/util.py
src/amltk/_util.py
src/amltk/evalutors/evaluation_protocol.py
src/amltk/optimization/history.py
src/amltk/optimization/optimizer.py
src/amltk/optimization/optimizers/neps.py
src/amltk/pipeline/node.py
src/amltk/scheduling/scheduler.py
src/amltk/scheduling/task.py
src/amltk/store/paths/path_bucket.py
src/amltk/types.py
tests/pipeline/test_optimize.py

TODO:
* Cleaning up documentation errors
* Creating a issue to re-write some of the optimization guide which should draw heavy attention to this feature.
Alright, buckle up, this is a bigger one (780 lines added).
The objective of this PR was to enable `pipeline.optimize(...)` to support fastest defaults towards just, well evaluating a pipeline, while still enabling it to extend out further into the future and not be too locked up in terms of use case.
Let's start with the simplest procedure:
```python
pipline = ...
history = pipeline.optimize(...)  # <- What needs to go in here
```
The first thing is the `.optimizer(target=...)` which should be a function that given a `Trial` and `Node` (pipeline), should return a `Trial.Report`, formally: `Callable[[Trial, Node], Trial.Report]`. This is …

feat(Pipeline): `optimize()`

---

docs/guides/optimization.md
docs/reference/optimization/history.md
examples/hpo.py
examples/hpo_with_ensembling.py
pyproject.toml
src/amltk/optimization/__init__.py
src/amltk/optimization/history.py
src/amltk/optimization/metric.py
src/amltk/optimization/optimizer.py
src/amltk/optimization/optimizers/neps.py
src/amltk/optimization/optimizers/optuna.py
src/amltk/optimization/optimizers/smac.py
src/amltk/optimization/trial.py
src/amltk/pipeline/node.py
src/amltk/scheduling/plugins/pynisher.py
src/amltk/store/paths/path_bucket.py
tests/optimizers/test_history.py
tests/optimizers/test_metric.py
tests/optimizers/test_optimizers.py
tests/pipeline/test_optimize.py
tests/scheduling/plugins/test_pynisher_plugin.py

This PR is namely just refactoring the `Metric` and where it was used to make it easier to go directly from `Metric` to `sklearn.metric._scorer._Scorer` or `_MultiScorer` in the next steps.
Notably, you can attach a `fn` to a `Metric` and call `as_sklearn_scorer(...) -> _Scorer` on it. This also applies to the new `MetricCollection(Mapping[str, Any])` where you can call `as_sklearn_scorer(...) -> _MultiMetricScorer`.
This enables the following improvement for sklearn integration:
```python
def evaluate(trial: Trial, pipeline: Node) -> Trial.Report:
model = (
pipeline.configure(trial.config).build("sklearn").set_output(transform="pandas")
)
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)
with trial.profile("fit"):
model.fit(X, y)
scorer = …
```

refactor(Metric, Trial): Cleanup of metrics and `Trial`

---

.gitignore
docs/guides/optimization.md
docs/hooks/cleanup_log_output.py
docs/reference/optimization/history.md
pyproject.toml
src/amltk/exceptions.py
src/amltk/optimization/__init__.py
src/amltk/optimization/evaluation.py
src/amltk/optimization/history.py
src/amltk/optimization/trial.py
src/amltk/pipeline/node.py
src/amltk/profiling/profiler.py
src/amltk/sklearn/__init__.py
src/amltk/sklearn/evaluation.py
src/amltk/store/__init__.py
src/amltk/store/bucket.py
src/amltk/store/drop.py
src/amltk/store/loader.py
src/amltk/store/paths/path_loaders.py
src/amltk/store/stored.py
tests/optimizers/test_history.py
tests/sklearn/test_evaluation.py

This PR mainly introduces the `amltk.sklearn.CVEvaluator`. This is something that can create a `Task[[Trial, Node], Trial.Report]` that can be optimized against for a proto-typical sklearn setup.
```python
from amltk.sklearn import CVEvaluation
from amltk.pipeline import Component, request
from amltk.optimization import Metric
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import get_scorer
pipeline = Component(
RandomForestClassifier,
config={"random_state": request("random_state")},
space={"n_estimators": (10, 100), "critera": ["gini", "entropy"]},
)
evaluator = CVEvaluation(
X,
y,
cv=3,
additional_scorers={"f1": get_scorer("f1")},
store_models=False,
train_score=True,
)
history = pipeline.optimize(
target=evaluator,
metrics=Metric("accuracy", minimize=False, …
```

feat(sklearn): Provide a standard CVEvaluator

---

src/amltk/exceptions.py
src/amltk/sklearn/evaluation.py
tests/sklearn/test_evaluation.py

Previously it would give the error but it was not really clear which trial failed. No it's explicitly in the error.

fix(CVEvaluator): When on_error="raise", inform of which trial failed

---

src/amltk/exceptions.py
src/amltk/pipeline/components.py
src/amltk/pipeline/node.py
tests/pipeline/test_node.py

This was causing an issue when configuring, where essentially the parent would steal the configuration of its child.
This problem came about where I had a pipeline named as the estimator, which could be a pretty
easy mistake to make.
```python
Sequential(
...,
...,
Component(
MLPClassifier,
name="mlp_classifier",
),
name="mlp_classifier",
)
```
I thought it only mattered that all children of a node must have unique names and that would be enough but nope, both the parent and it's children must be uniquily named too.
```python
Traceback (most recent call last):
File "/home/skantify/code/exps/one.py", line 12, in <module>
from exps.pipelines import knn_classifier, mlp_classifier, rf_classifier
File "/home/skantify/code/exps/src/exps/pipelines.py", line 176, in <module>
mlp_classifier = …
```

fix(Node): Ensure that parent name does not conflict with children

---

src/amltk/sklearn/evaluation.py

Whoops, somehow the estimator wasn't getting cloned before being CVFitted on. This
wasn't caught by the tests as the default model we used could be warm-started and refit without issue. I ran across this bug while using this on an MLPClassifier.

fix(CVEvaluator): `clone` the estimator before use

---

src/amltk/sklearn/evaluation.py
tests/sklearn/test_evaluation.py

Cleans up some TODO's and makes the CVEvaluator more flexible for experienced users.
Docstrings provided.
```python
pipeline = Component(
RandomForestClassifier,
config={
"n_jobs": request("n_jobs", default=None)
},
space={"n_estimators": (10, 100), "criterion": ["gini", "entropy"]},
)
evaluator = CVEvaluation(
X,
y,
params={"configure": {"n_jobs": 2}}
)
history = pipeline.optimize(...)
```
Same can be done to interact with `build()`, for example, to build with an `ImblearnPipeline` or use your own custom builder.
```python
from imblearn.pipeline import Pipeline as ImbalancedPipeline
CVEvaluator(
...,
params={
"build": {
"builder": "sklearn",
"pipeline_type": ImbalancedPipeline
}
}
)
```
Same exmaples given in docstrings

feat(sklearn): CVEvaluator allows `configure` and `build` params

---

src/amltk/pipeline/node.py
src/amltk/sklearn/evaluation.py

Having a `max_trials` defaulting to `3` was dump in retrospect as you may have expected that setting `timeout` would mean it would keep going until that timeout was reached.
Now one of the two must be specified, either `max_trials` or `timeout`.

refactor(pipeline): `optimize` now requires one of `timeout` or

---

docs/api_generator.py
docs/guides/scheduling.md
examples/hpo.py
src/amltk/exceptions.py
src/amltk/optimization/__init__.py
src/amltk/optimization/evaluation.py
src/amltk/optimization/metric.py
src/amltk/optimization/trial.py
src/amltk/pipeline/node.py
src/amltk/scheduling/events.py
src/amltk/scheduling/plugins/comm.py
src/amltk/scheduling/plugins/emissions_tracker_plugin.py
src/amltk/scheduling/plugins/limiter.py
src/amltk/scheduling/plugins/plugin.py
src/amltk/scheduling/plugins/pynisher.py
src/amltk/scheduling/plugins/threadpoolctl.py
src/amltk/scheduling/plugins/wandb.py
src/amltk/scheduling/plugins/warning_filter.py
src/amltk/scheduling/scheduler.py
src/amltk/scheduling/task.py
src/amltk/sklearn/evaluation.py
tests/scheduling/plugins/test_comm_plugin.py
tests/sklearn/test_evaluation.py

Alright, another big one.
Major feature was to implement CVEarlyStopping. This will need to be documented once the optimization documentation gets updated. There also needs to be some default variants select-able by keyword but for now that's the subject of experimentation.
---
```python
class CVEarlyStopper:
def __init__(self, metric: Metric, threshold: float):
super().__init__()
self.threshold = threshold
self.metric = metric
def update(self, report: Trial.Report) -> None:
pass # Normally you would update w.r.t. a finished trial
def should_stop(self, info: CVEvaluation.FoldInfo) -> bool:
return info.scores[self.metric.name] < self.threshold
metric = Metric("accuracy", minimize=False)
evaluator = CVEvaluation(_X, _y)
early_stopper = CVEarlyStopper(metric=metric, threshold=0.8)
history = …
```

feat: CVEarlyStopping

---

src/amltk/scheduling/termination_strategies.py

* Closes #255 
The main fix here is to wrap the `psutil.Process(...)` construction in case the process no longer exists by the time it gets there. Another addition to the fix is first, reversing child traversal order, processing leaf processes first, terminating them and then moving up the tree. This gives parent processes time to respond and handle accordingly.
Lastly, we introduce a `polite_kill(process: psutil.Process)` that first tries to send a `SIGTERM` and the follows up with a `SIGKILL` after 5 seconds. I have had no cases where `terminate() [SIGTERM]` has not terminated a process within 1 second but rogue processes may not respond to `SIGTERM`, hence a follow up of `SIGKILL` after a gracious time buffer.

fix(scheduling): Safe termination of processes, avoiding lifetime race condition

---

src/amltk/sklearn/evaluation.py
tests/sklearn/test_evaluation.py

This PR implements the ability to pass a test set, specifically an `X_test` and a `y_test` to `CVEvaluator`. All provided scorers will be computed on the test set if provided and recorded in the report, as it is with `train_scores`.
These are available in `report.summary` as `"test_mean_{metric}"`, `"test_std_{metric}"` and also `"split_{i}:test_{metric}"` for each split, just as with train scores.
For most cases, the usage is rather straight forward. For passing custom parameters to the scorers at test time, all scorer parameters must be prefixed with `"test_{key}"`, i.e.
```python
CVEvaluator(
X, y,
X_test=X_test, y_test=y_test,
params={
"sample_weight": sample_weight,
"test_sample_weight": test_sample_weight,
"pos_label": 0,
"test_pos_label": 0,  # Note that it needs to be duplicated. …
```

feat(sklearn): `X_test`, `y_test` to CVEvaluator

---

src/amltk/sklearn/evaluation.py
tests/sklearn/test_evaluation.py

tldr; callback hooks after each split evaluation that has access to all data and model as well as a callback hook as the last step before reporting back from the worker. Both callbacks are serialized and called **inside the worker**, therefore they have more access to data without worrying about serialization _out of_ the worker.
Tradeoff for this is that they can not freely access information from main process and should be lightweight, as these callbacks get serialized _into_ the worker.
Tried to ensure no data lives longer than it needs to to prevent split data/models living longer than needed.
Will fill this description better once I've tested it a bit more. 
---
@LennartPurucker this refactor is pretty unreviewable by the git diffs so I hope the tests illustrate what's possible: …

feat(CVEvaluator): Add feature for post_split and post_processing

---

examples/pytorch-example.py
src/amltk/pytorch/builders.py
tests/pytorch/test_match_dimensions.py

* Fixes pre-commit errors
* Convert `MatchXXX` to simple dataclasses
* Fix some small issues with respect to typing
* Refactor to use `match` statements
---
The motivation behind `match` is it lets the type checker know a bit more about what you want to do, i.e. exhaustively handling of cases. When using `if` statements, if you forget an `else`, it won't complain, however when using a `match` statement, it says you haven't handled all cases.
```python
node: Node
match node:  # Error: You havn't exhaustively handled all cases
case Component():
pass
case Fixed():
pass
#####
node: Node
if isinstance(node, Component):
pass
elif isistnance(node, Fixed):
pass
```

fix: precommit issues from #276

---

src/amltk/pytorch/builders.py
tests/pytorch/test_build_model_from_pipeline.py

Add fix to handle Fixed layers (e.g. activations) which are not wrapped in the `Fixed` class wrapper. Or any other torch nodes which are placed directly by the user, without wrapping them in the `Component` class.

fix(Pytorch): Fix builders.py

---

src/amltk/pipeline/node.py

Previously when serialized to a new process, object ids would no longer match, causing the `has_default` check to succeed, even if not set.

fix(pipeline): `request` now fails without default

---

.github/workflows/release.yml

I could've opened a separate issue, but I figured a PR makes it easier to view my suggestion.
When looking at this workflow I noticed that there seems to be an extraneous Python setup step in the citizen bump job. As far as I can tell, it serves no purpose. In my work-in-progress workflow I left it out without issue.
Run the workflow (on a fork where it is not a trusted PyPI publisher...). I tried it [here](https://github.com/PGijsbers/amltk/actions/runs/9197051255/job/25296590574), but unfortunately the docs step already seems to be failing, so it won't show a successful bump. So that step would need to be resolved first, but it's unrelated to this PR. After that, you _should_ see that indeed the Python setup step is not necessary to execute the bump job and you can release [23 …

ci: Remove unnecessary Python setup step
